#!/usr/bin/env php
<?php
/**
 * Ozi Script Command Line Development Tool
 * Use this to manage screens, widgets, plugins, and serve your application.
 */

require "system_config.php";
require "system_files/libraries/ozi_comands/comands.php";
require "system_files/libraries/ozi_comands/comands_args.php";
require "system_files/libraries/ozi_comands/check_comands_exist.php";
