<?php
/*starting a session, this allows you to store data in $_SESSION['data'] in any of your components*/
session_start();
//echo ini_get("session.gc_maxlifetime"), "\n";

/** BELOW ARE THE REQUIRED DEPENDENCIES FOR OZI SCRIPT, PLUGIN AND WIDGETS ARE TO BE COMMENTED or UNCOMMENTED IF NOT IN USE. You Can Add New Labraries If You Know How It Works.. Learn More At https://oziscript.com */







/*=======  SYSTEM CONFIGURE (DONT EDIT ONLY USE CLI ADD OR REMOVE DEPENDENCIES) ============*/
/*=======  SYSTEM CONFIGURE (DONT EDIT ONLY USE CLI ADD OR REMOVE DEPENDENCIES) ============*/
/*=======  SYSTEM CONFIGURE (DONT EDIT ONLY USE CLI ADD OR REMOVE DEPENDENCIES) ============*/
/*=======  SYSTEM CONFIGURE (DONT EDIT ONLY USE CLI ADD OR REMOVE DEPENDENCIES) ============*/
/*=======  SYSTEM CONFIGURE (DONT EDIT ONLY USE CLI ADD OR REMOVE DEPENDENCIES) ============*/
/*=======  SYSTEM CONFIGURE (DONT EDIT ONLY USE CLI ADD OR REMOVE DEPENDENCIES) ============*/
$files = [
    'libraries' => [
        /*=======  GETTING LIBRARIES FILES ....  ============*/

        //calling app router Lib
        require "system_files/libraries/router.php",
        //calling cssd lib
        require "system_files/libraries/cssd.php",
        //calling jsd lib
        require "system_files/libraries/jsd.php",
        //calling iosMedia lib
        require "system_files/libraries/ios_media.php",

        /*=======  END OF GETTING LIRARIES FILES ....  ============*/

    ],

    'plugins' => [
        /*=======  GETTING PLUGIN FILES ....  ============*/

        //Getting mail_agent plugin
        //require 'system_files/plugins/mail_agent/index.php',
        //Getting Carbon plugin
        //require 'system_files/plugins/carbon/index.php',

        /*=======  END OF GETTING PLUGIN FILES ....  ============*/],


    'widgets' => [
        /*=======  GETTING WIDGETS FILES ....  ============*/
   
/*=======  END GETTING WIDGETS FILES .... ============*/],


    'system_setup' => [
        /*=======  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/

        //004 Getting the file that is required to for building your app screen
        require 'view.php',

        //003 Getting required file for your uert interface (UI) design
        require 'ui_config.php',

        //002 Getting required BackEnd config 
        require "create_bk_request.php",

        //001 Getting required BackEnd config
        require "call_bk_request.php",

        /*=======END OF  SYSTEM REQUIRED FILES, DO NOT EDIT THIS FILES BELOW....  ============*/
    ],

];
