#!/usr/bin/env php
<?php

// Define commands
require "system_files/libraries/ozi_comands/comands.php";

// Get command and arguments
require "system_files/libraries/ozi_comands/comands_args.php";


// Check if command exists
require "system_files/libraries/ozi_comands/check_comands_exist.php";
